# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to get ChiSquare
#'
#' @param par vector of breaks
#' @param muts mutations vector
#' @param L genome length
#' @return ChiSquare
#' @export
getChiSquare <- function(par, muts, L) {
    .Call('_segmut_getChiSquare', PACKAGE = 'segmut', par, muts, L)
}

#' function to get new best break
#'
#' @param muts vector of mutations
#' @param L genome length
#' @param parPrev exististing breaks (including 0 and L)
#' @return new break
#' @export
getBestSingleBreak <- function(muts, L, parPrev) {
    .Call('_segmut_getBestSingleBreak', PACKAGE = 'segmut', muts, L, parPrev)
}

#' function to improve the breaks.
#'
#' @param muts vector of mutations
#' @param L genome length
#' @param par breaks (including 0 and L)
#' @return breaks
#' @export
improve <- function(muts, L, par) {
    .Call('_segmut_improve', PACKAGE = 'segmut', muts, L=0, par=c(0,L))
}

