# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' function to improve the breaks.
#'
#' @param muts vector of mutations
#' @param L genome length
#' @param par breaks (including 0 and L)
#' @return breaks
improve <- function(muts, L, par) {
    .Call('_segmut_improve', PACKAGE = 'segmut', muts, L, par)
}

